esphome:
  includes:
    - opentherm.h
    - opentherm.cpp
    - opentherm_gw_climate.h
    - opentherm_gw_climate.cpp
  name: opentherm_gateway
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


# Enable logging
logger:
  baud_rate: 0
  level: DEBUG  

api:
ota:
web_server:
  port: 80

sensor:
binary_sensor:

climate:
- platform: custom
  lambda: |- 
    auto thermostat_in = new GPIOPin(26, INPUT);
    auto thermostat_out = new GPIOPin(17, OUTPUT);
    auto boiler_in = new GPIOPin(25, INPUT);
    auto boiler_out = new GPIOPin(16, OUTPUT);
    auto ca = new esphome::opentherm::OpenThermGWClimate(thermostat_in, thermostat_out, boiler_in, boiler_out);
    App.register_component(ca);
    App.register_climate(ca);
    return {ca};
  climates:
    - name: "livingroom"   